### ISSUE TITLE
Missing Snapshot Contents

### ISSUE THREAD

**Issue by gwincr11** [nanoc/nanoc#1342] opened 2018-07-23 20:33 UTC
Errors during build post step that iterates over @items and gets the compiled contents.

### Steps to reproduce

1. Build a really really Nanoc large site.
1. Updating from 4.3.2 to 4.9.2
1. add a postprocess that iterates over `@items.each do |item|`
1. call `item.compiled_content`

### Expected behavior

We should get all the html contents for each file as we iterate

### Actual behavior

Certain items fail here: https://github.com/nanoc/nanoc/blob/master/nanoc/lib/nanoc/base/views/post_compile_item_rep_view.rb#L13
With the error 
`NoMethodError: undefined method []' for nil:NilClass`

### Crash log

I can make a private Gist if I know who to share it with.

**Comment by ddfreyne** [comment] 2018-07-27 07:09
@gwincr11 Can you share the crash log with me?

**Comment by gwincr11** [comment] 2018-07-27 14:02
@ddfreyne I have sent you a link thanks for taking a 👀

**Comment by ddfreyne** [comment] 2018-07-27 19:43
@gwincr11 I took a look but I’m unable to reproduce the issue.

Could you re-run Nanoc with run-time contracts enabled? To do so:

1. Add `gem 'contracts', '~> 0.16'` to the Gemfile
2. Run `bundle install`
3. Re-run Nanoc

If we’re lucky, there is a contract failure that pinpoints the problem more precisely.

**Comment by gwincr11** [comment] 2018-08-03 19:58
@ddfreyne I have updated the gist, after adding the gem. Thanks!

**Comment by ddfreyne** [comment] 2018-08-17 09:01
@gwincr11 Hey Cory, I reached out to you privately — could you let me know whether this issue is still relevant?

**Comment by ddfreyne** [comment] 2018-08-19 08:31
@gwincr11 Hey, I’ve got a potential fix in #1349, already merged into `master`. Can you give Nanoc from Git a try?

**Comment by ddfreyne** [comment] 2018-08-19 08:50
The just-released Nanoc 4.9.4 has this fix. Can you upgrade Nanoc and give it another try?

I will close the issue because I’m optimistic that the bug is indeed fixed, but please let me know if the issue persists!

**Closed by ddfreyne** 2018-08-19 08:50 UTC
Labels: type:bug :bug:
