### ISSUE TITLE
Big 0-change compilation performance regression

### ISSUE THREAD

**Issue by da2x** [nanoc/nanoc#1605] opened 2022-10-19 15:20 UTC
1. bundle update
2. time bundle exec nanoc compile
3. repeat step 2. eleven times, discard first run, and average results.

```
4.12.10:  47,02s
4.12.9:  108,04s
4.12.8:    5,38s
4.12.7:    5,40s
```

My site consists of roughly 3500 items.

rbspy nanoc 4.12.10 flamegraph (below) and [raw](https://github.com/nanoc/nanoc/files/9821703/2022-10-19-rQAOEXcARE.raw.gz):

![2022-10-19-tcFeP7YFAO flamegraph](https://user-images.githubusercontent.com/1102886/196730277-8ecb6647-4cc3-4fd8-a6cd-7b1b373eea07.svg)

rbspy nanoc 4.12.8 flamegraph (below) and [raw](https://github.com/nanoc/nanoc/files/9821795/2022-10-19-7Zm6JymvJK.raw.gz):

![2022-10-19-WlwSxgxNGk flamegraph](https://user-images.githubusercontent.com/1102886/196733284-eb12b2b2-e8c8-4499-82ce-4300d14b7e37.svg)

ruby-3.1.1-162.fc36

**Comment by denisdefreyne** [comment] 2022-10-19 16:26
Whoa, that’s quite a significant slowdown! At least I’m glad that the 4.12.10 speed improvements made it slightly less bad… :)

Which site is this for, and can I test it out locally? The flamegraphs are useful already, though not enough to figure out what is going on .

**Comment by denisdefreyne** [comment] 2022-10-22 20:20
I’ve been meaning to give the outdatedness checker a significant overhaul, which would solve this issue and improve performance beyond even v4.12.8’s level. I think the time to do this is now, and #1607 is the first step towards making that happen.

> my sitemaps aren’t reliably regenerated when changing content files

Could you be a bit more specific about what you see happening (or not happening)? Under which circumstances would you expect the sitemap to be regenerated, and what would the changes to the compiled sitemap be like?

**Comment by denisdefreyne** [comment] 2022-10-24 17:08
I’ve made at attempt at reproducing the sitemap issue, without success unfortunately. I was tripped up by a couple of things though:

- `@items['/entry/*.html']`: This probably needs to use `find_all`, like `@items.find_all('/entry/*.html')`. Correct? [] returns a single item, but `find_all` returns a collection.

- `sort_by { entry[:created_at].to_s }`: there’s probably a `|entry|` missing just after the `{` -- correct?

- The `%FT%R:00Z` format string drops seconds and sets them to 0. This means that the sitemap would seem not to be regenerated if the entries have been changed in the exact same minute. I’m assuming that this is *not* what is happening -- correct? (Running `nanoc compile` with `--verbose` should show `identical` for the sitemap, rather than `skip`.)

---

I’ve also had a look at the slowness itself, but I’ve not made much progress there either. The irony is that the changes in the last two Nanoc versions had the intention of *speeding Nanoc up*. 

Can you share the output of `nanoc show-data` with me? That’d be immensely useful for debugging purposes. If you prefer that output to be kept private, you can share it with me as a secret gist and DM me at [@ddfreyne](https://twitter.com/ddfreyne).

**Comment by da2x** [comment] 2022-10-24 18:05
> I’ve made at attempt at reproducing the sitemap issue, without success unfortunately. I was tripped up by a couple of things though:
> 
>     * `@items['/entry/*.html']`: This probably needs to use `find_all`, like `@items.find_all('/entry/*.html')`. Correct? [] returns a single item, but `find_all` returns a collection.

Yes, this was supposed to be a `@items.find_all('/entry/*.html')`. I quickly and mistakenly rewrote this from `entries.sort_by…`   where `entries = @items.find_all('/entry/*.html')` was defined earlier. (I’m doing other stuff with the `entries` and also trying to not do duplicated `@items.find_all` lookups because they’re slow when dealing with lots of items. Maybe I should have opened a enhancement request for memoizing `find_all` instead.) Sorry about that.

>     * `sort_by { entry[:created_at].to_s }`: there’s probably a `|entry|` missing just after the `{` -- correct?

Indeed. I did a poor job of copy and paste here.

>     * The `%FT%R:00Z` format string drops seconds and sets them to 0. This means that the sitemap would seem not to be regenerated if the entries have been changed in the exact same minute. I’m assuming that this is _not_ what is happening -- correct? (Running `nanoc compile` with `--verbose` should show `identical` for the sitemap, rather than `skip`.)

I ran it with 65 sec sleep after touching the file overnight, so that’s not the case. Also, if this was the issue then it should have seen the problem with the faster version and not the slower version. :wink:

> I’ve also had a look at the slowness itself, but I’ve not made much progress there either. The irony is that the changes in the last two Nanoc versions had the intention of _speeding Nanoc up_.
> 
> Can you share the output of `nanoc show-data` with me? That’d be immensely useful for debugging purposes. If you prefer that output to be kept private, you can share it with me as a secret gist and DM me at [@ddfreyne](https://twitter.com/ddfreyne).

https://gist.githubusercontent.com/da2x/078eec513aa58a96107b4b89387fd994/raw/5c93955d1fede218c746a3a32532e47f377a8c7c/nanoc%2520show-data

**Comment by da2x** [comment] 2022-10-24 23:05
Oh, I completely forgot to include the `--debug`!

```
bundle exec nanoc compile --verbose --debug # [01:01:17] 
Loading site… done
Compiling site…
*** 01:01:20.148 Stage started: LoadStores
*** 01:01:20.586 Stage ended: LoadStores
*** 01:01:20.586 Stage started: CalculateChecksums
*** 01:01:21.426 Stage ended: CalculateChecksums
*** 01:01:21.426 Stage started: DetermineOutdatedness
*** 01:02:05.614 Stage ended: DetermineOutdatedness
*** 01:02:05.614 Stage started: ForgetOutdatedDependencies
*** 01:02:05.615 Stage ended: ForgetOutdatedDependencies
*** 01:02:05.615 Stage started: StorePreCompilationState
*** 01:02:05.759 Stage ended: StorePreCompilationState
*** 01:02:05.765 Stage started: Prune
*** 01:02:05.802 Stage ended: Prune
*** 01:02:05.802 Stage started: CompileReps
*** 01:02:06.204 Stage ended: CompileReps
*** 01:02:06.204 Stage started: StorePostCompilationState
*** 01:02:06.499 Stage ended: StorePostCompilationState
*** 01:02:06.499 Stage started: Postprocess
*** 01:02:06.499 Stage ended: Postprocess
*** 01:02:06.500 Stage started: Cleanup
*** 01:02:06.501 Stage ended: Cleanup
[        skip  items…]
Site compiled in 48.09s.
```

**Comment by denisdefreyne** [comment] 2022-10-29 07:14
@da2x Can you check whether the latest `main` fixes the performance issue you’re seeing? I suspect that efe051cca16c06e6a74d282f3cfd2c1d1c39b898 will make a difference.

To use Nanoc from Git, you can use this in your Gemfile:

```ruby
  gem 'nanoc', git: 'https://github.com/nanoc/nanoc', glob: 'nanoc/*.gemspec'
  gem 'nanoc-cli', git: 'https://github.com/nanoc/nanoc', glob: 'nanoc-cli/*.gemspec'
  gem 'nanoc-core', git: 'https://github.com/nanoc/nanoc', glob: 'nanoc-core/*.gemspec'
```

**Comment by da2x** [comment] 2022-10-29 12:42
@denisdefreyne, `50.12s` (average of ten runs) – reverting to `4.12.10` speeds it back up to `~47s`.

**Comment by denisdefreyne** [comment] 2022-10-29 15:19
Ouch. I’m still struggling to figure out the cause of the slowdown, but will keep at it.

**Comment by da2x** [comment] 2022-10-29 19:42
I’m going through the compilation stages with strace now. Found something else:
There’s one call to `clock_gettime()` per source item. Not a regression, but it’s also slowing things down. This is probably from a `Time.now` that could be cached to speed things up. Unless Nanoc really needs an updated with microsecond-precision timestamp somewhere, of course.

**Comment by da2x** [comment] 2022-10-29 21:13
Something in [`raw_content_prop_causes_outdatedness?`](https://github.com/nanoc/nanoc/blob/019059b15a7d8fbac60a64ff00f70da24a25a954/nanoc-core/lib/nanoc/core/outdatedness_checker.rb#L140) calls 
`String.match?`, as also shown in the visualization by rsbpy. `match?` causes a memory allocation (anonymous `mmap()`) of 32768 bytes per compiled item that is immediately freed. The thousand of short-lived memory allocations are causing the slowdown.

**Comment by da2x** [comment] 2022-10-29 23:17
The memory allocations are entirely unused (zeroed) and freed immediately. And rbspy and myself miss-attributed it to `raw_content_prop_causes_outdatedness?`. They happens slightly earlier, but I can’t quite track down where.

**Comment by denisdefreyne** [comment] 2022-10-30 08:58
In https://github.com/nanoc/nanoc/commit/efe051cca16c06e6a74d282f3cfd2c1d1c39b898 the `#match?` is replaced with a `#find_all` on the item collection. That `#find_all` still uses `#match?` under the hood, but the `#find_all` call is memoized, which I had hoped would be enough to fix the performance issue.

This might be silly, but can you confirm that you’re on the latest `main`?

If you are, could you run rbspy again, and create a report with `rbspy report --format speedscope`? That’d allow me to use [speedscope](https://www.speedscope.app/) which I like a lot for dealing with flame graphs.

**Comment by da2x** [comment] 2022-10-31 12:22
> This might be silly, but can you confirm that you’re on the latest `main`?

2c28f9d90be656cb89bcc148001f2671594d1125 confirmed.

> If you are, could you run rbspy again, and create a report with `rbspy report --format speedscope`?

Here you go:

  * [2022-10-31-Q0WZ23yGLo.speedscope.json.gz](https://github.com/nanoc/nanoc/files/9900972/2022-10-31-Q0WZ23yGLo.speedscope.json.gz)
  * [2022-10-31-u2dlHF8bbo.raw.gz](https://github.com/nanoc/nanoc/files/9900973/2022-10-31-u2dlHF8bbo.raw.gz)

**Comment by denisdefreyne** [comment] 2022-11-01 19:48
Could you try replacing the following

```
<%  urls = @items
    .find_all("{#{@item[:entries].join(',')}}")
    .…
```

… with this:

```
<%  urls = @item[:entries]
    .map { |entry| @items[entry] }
    .…
```

`#find_all` is not the fastest, but that’s usually fine because the results are cached. In your case though, because you’re calling `#find_all` with collections of elements that are often different, the cache isn’t used well.

Does this change -- here and possibly in other parts of your code -- bring Nanoc back up to its original speed?

---

One improvement to Nanoc that I’ve been putting off is an efficient way to query items by glob, but I believe it’d require a custom data structure and a glob compiler, for which I might not be up to the task.

**Comment by da2x** [comment] 2022-11-02 21:26
> Does this change -- here and possibly in other parts of your code -- bring Nanoc back up to its original speed?

No. I swapped out find_all everywhere with `[].map{|e|@items[e]}`. I also swapped all globs with hardcoded arrays. Nanoc compilation got slightly ***slower*** compared to the existing code with globs.

**Comment by denisdefreyne** [comment] 2022-11-05 08:48
Oh no!

Could you run `rbspy` again on the version without `find_all`, and then send me the speedscope-formatted results? (`rbspy report --format speedscope`)

I’m still fairly in the dark, especially as the recent changes to Nanoc have improved site compilation speed of all the sites I have!

**Comment by da2x** [comment] 2022-11-05 11:28
[2022-11-05-XhfpxIjXVu.speedscope.json.gz](https://github.com/nanoc/nanoc/files/9943652/2022-11-05-XhfpxIjXVu.speedscope.json.gz)
[2022-11-05-PCCKKYx6u7.raw.gz](https://github.com/nanoc/nanoc/files/9943655/2022-11-05-PCCKKYx6u7.raw.gz)

**Comment by denisdefreyne** [comment] 2022-11-05 11:56
@da2x Are these the results running on the latest `main` branch? (Following the steps I outlined [in this comment](https://github.com/nanoc/nanoc/issues/1605#issuecomment-1295756820))? If so, it looks like `main` is back to 5.5s, which would be good.

**Comment by da2x** [comment] 2022-11-05 12:49
Sorry! Those were from the wrong version. I ran both for my own reference and uploaded the wrong version.

Here’s from `main`:

* [2022-11-05-Y4DJMcMG6q.speedscope.json.gz](https://github.com/nanoc/nanoc/files/9943825/2022-11-05-Y4DJMcMG6q.speedscope.json.gz)
* [2022-11-05-hDmwro2baK.raw.gz](https://github.com/nanoc/nanoc/files/9943826/2022-11-05-hDmwro2baK.raw.gz)

**Comment by denisdefreyne** [comment] 2022-11-05 13:53
Thanks! I think I’m on to something — will let you know when I have news.

**Comment by da2x** [comment] 2022-11-05 14:57
6527edab8c913af01ebf3ec379beeb381e0fc66e improved things significantly! 11,5 seconds!

**Comment by denisdefreyne** [comment] 2022-11-05 15:15
@da2x Can I get you to test out the `denis/optimize-single-item-dependencies` branch as well?

For your Gemfile:

```
  gem 'nanoc',      git: 'https://github.com/nanoc/nanoc', branch: 'denis/optimize-single-item-dependencies', glob: 'nanoc/*.gemspec'
  gem 'nanoc-cli',  git: 'https://github.com/nanoc/nanoc', branch: 'denis/optimize-single-item-dependencies', glob: 'nanoc-cli/*.gemspec'
  gem 'nanoc-core', git: 'https://github.com/nanoc/nanoc', branch: 'denis/optimize-single-item-dependencies', glob: 'nanoc-core/*.gemspec'
```

To see the changes, you might have to delete `tmp/nanoc` and run `nanoc` twice or so, make a few changes, and run `nanoc` again.

**Comment by da2x** [comment] 2022-11-05 15:28
> @da2x Can I get you to test out the `denis/optimize-single-item-dependencies` branch (PR #1613) as well?

8,9s

> To see the changes, you might have to delete `tmp/nanoc` and run `nanoc` twice or so, make a few changes, and run `nanoc` again.

I’ve already been deleting tmp/nanoc when switching versions. :wink:

This change had another, possibly unexpected, side-effect. My single-entry-changed compilation time has always been around 30s. A bit annoying, but whatever — it’s what I’ve been used to. This change — or maybe the combination of changes — brought it down to 13 seconds.

**Comment by denisdefreyne** [comment] 2022-11-05 15:40
Nice!

It’d be good to get another speedscope-formatted rbspy profile too!

**Comment by da2x** [comment] 2022-11-05 15:58
From 2f8cef94bc5a on zero-change compilations:

* [2022-11-05-G3lZyrYqBC.speedscope.json.gz](https://github.com/nanoc/nanoc/files/9944192/2022-11-05-G3lZyrYqBC.speedscope.json.gz)
* [2022-11-05-hQJDmx3KwH.raw.gz](https://github.com/nanoc/nanoc/files/9944194/2022-11-05-hQJDmx3KwH.raw.gz)

**Comment by denisdefreyne** [comment] 2022-11-12 10:41
I think this issue is close to being closed, but there are a few things I’d like to look at still.

In any case, I released Nanoc 4.12.11 today.

**Comment by denisdefreyne** [comment] 2022-11-15 17:15
@da2x Could you clarify whether the profile results are measures with code that uses `#find_all`, or code that uses `<% urls = @item[:entries].map { |entry| @items[entry] }.…` instead?

**Comment by denisdefreyne** [comment] 2022-11-21 20:04
@da2x Also — are you seeing the problem with sitemap mis-compilation still? I’ve not been able to reproduce that.

**Comment by da2x** [comment] 2022-12-05 18:53
Sorry about the late response. (I’ve just started a new job.) The last rbspy was using with the map-based method. I can’t reproduce the sitemap issue now even when using the old versions and when rolling back to my old code. I’ve updated from a Ryzen 3700 to a 5700X, so my single-core performance is up roughly 30%. This could interfere with the results, assuming it was a timing issue. The CPU upgrade got my zero-change compilation time down from 8,9s to 6,76s.

**Comment by denisdefreyne** [comment] 2022-12-17 10:35
Thanks for the reply!

Good to hear that the site is working again, though timing issues are a little scary. I’ve not seen issues like this anytime recently, and have not been able to reproduce it. I’m definitely keeping my eye on it, though.

As for the compilation speed: I’ve been more focused on getting the compilation speed of 1+ changes down, rather than zero changes. So, even though the latest Nanoc version is still slower on 0 changes (5.4s -> 8.9s), I’m inclined to mark this issue as closed. What do you think?

**Comment by denisdefreyne** [comment] 2023-10-14 19:53
I’ll close this for now. If there are performance issues that are cause for concern, let me know!

**Closed by denisdefreyne** 2023-10-14 19:53 UTC
Labels: type:bug :bug:
