### ISSUE TITLE
Compilation regression in nanoc v4.6.2

### ISSUE THREAD

**Issue by grobie** [nanoc/nanoc#1106] opened 2017-03-05 01:59 UTC
Compilation won't finish (in minutes) with v4.6.2. Reverting to v4.6.1 results in the expected fast compilation (`Site compiled in 0.34s.`).

### Steps to reproduce

1. `bundle exec nanoc`

### Expected behavior

Compile the site in a reasonable time.

### Actual behavior

Nothing happens for minutes and I have to manually abort. nanoc uses a 100% of one of my CPU cores.

**Comment by ddfreyne** [comment] 2017-03-05 09:02
Ah, the room-heating feature!

Do you have reproduction that I can use for debugging this issue? I’m not able to reproduce it locally.

**Comment by elomatreb** [comment] 2017-03-05 09:33
If this gets fixed, [please add an option to reenable ~~spacebar~~ compilation heating](https://xkcd.com/1172/).

**Comment by Fjan** [comment] 2017-03-05 11:47
I see the same issue on two different nanoc sites, but not on a third (although the third one got a bit slower too). The compilation does eventually complete after a long time on the smallest of the two sites, so it's probably not an endless loop. 

Putting ```puts "#{Time.now}\t#{item.identifier}"``` inside the ```compile``` block in the Rules files show all files getting compiled twice in a row, and take several seconds per compile. Not a repo I can share easily, sorry.

**Comment by grobie** [comment] 2017-03-05 12:31
https://github.com/promcon/website/pull/6 don't spread the word yet please.

**Comment by ddfreyne** [comment] 2017-03-05 12:32
The compile block being called twice for every item rep is expected; this is part of the initial process of recording the compilation rules and paths. Once that process is complete, the actual compilation will start.

What strikes me as odd is that this is supposed to be quite fast (on the nanoc.ws site, the entire process takes about 1s).

**Comment by ddfreyne** [comment] 2017-03-05 12:40
It seems like I already fixed this on `master` earlier, because I cannot reproduce this any more for the Promcon web site:

```
Site compiled in 0.55s.
```

**Comment by ddfreyne** [comment] 2017-03-05 12:40
Yeah, looks like this was the culprit: b83ac1817ed70c4eec0bb53f1e0d22a9e1c7b27a.

**Comment by ddfreyne** [comment] 2017-03-05 12:41
I’ll close this for now, but LMK if this is still a problem!

**Closed by ddfreyne** 2017-03-05 12:41 UTC
Labels: bug

**Comment by ddfreyne** [comment] 2017-03-05 12:52
This is released in Nanoc 4.6.3.

**Comment by grobie** [comment] 2017-03-05 13:17
Thanks!

**Comment by Fjan** [comment] 2017-03-05 13:34
Yep, 4.6.3 fixes this :+1:
