### ISSUE TITLE
How to record an explicit dependency

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1091] opened 2017-02-28 20:33 UTC
I have Sass files that need to read the compiled output of binary items. Nanoc's compilation order should follow suit and compile the binary first and then the Sass. If it happens that Sass is compiled first, it needs to be retried later when the binaries are available. I found `Nanoc::Int::Errors::UnmetDependency` and wonder if I can use it.

So far I have some up with this, but unfortunately it doesn't work.

```rb

class WhatTheSassFilterWouldDoIsThis < Nanoc::Filter
  identifier :test
  @@counter = 0

  def run(content, args = {})
    @@counter += 1
    puts "filter attempt #{@@counter}"

    # "other" would be an item referenced/pulled by a Sass::Script function.
    other = @items['/dependency.html']

    # First Sass compilation attempt where the binaryis not yet compiled.
    if @@counter == 1
      puts "raising"
      raise Nanoc::Int::Errors::UnmetDependency.new(other.reps.first.unwrap)
    end

    # Second attempt, binary is available.
    puts 'returning content'
    other.reps.first.compiled_content
  end
end
```

Why all that? I want to read the sizes of binary items. First I need to pull the nanoc-generated output path of the binary item (that might change because of cache-busting) and feed that to Sass image-processing functions. The file needs to be there (compiled), just the path would make Sass fail to open the file in order to read its dimensions.

**Comment by ddfreyne** [comment] 2017-02-28 20:39
There’s a method `#depend_on` in `Nanoc::Filter` which does what you need:

```ruby
class WhatTheSassFilterWouldDoIsThis < Nanoc::Filter
  identifier :test

  def run(content, args = {})
    other = @items['/dependency.html']
    depend_on(other)
    # … do something with other.path …
  end
end
```

**Comment by ddfreyne** [comment] 2017-02-28 20:39
(Using something such as `@@counter` is unlikely to work due to thread safety issues.)

**Comment by agross** [comment] 2017-02-28 22:30
It seems `depend_on` does not abort the current filter. How would I do that?

The process is as follows (assuming empty output directory)
1. `bundle exec nanoc`
1. `:sass` filter runs
1. A sass file calls my custom Sass::Script
1. Script obtains item 
1. Script checks if item is compiled, it isn't hence call `depend_on(item)`
1. Script returns item rep's path to Sass
1. Sass tries to read the file for the path
1. 💥

Essentially I need to abort the Sass filter without aborting the whole Nanoc compiler. Just to signal "Sass needs some items to be compiled first".

If you're interested, here's the Sass::Script:

```rb
require 'nanoc'
require 'sass'

module Sass
  module Script
    module Items
      def i(identifier, kwargs = {})
        item = find_item(identifier.value)

        item_rep = item_rep_named(item, kwargs.fetch('rep', :default))

        options[:nanoc_current_filter].depend_on([item])
        # raise Nanoc::Int::Errors::UnmetDependency.new(item_rep.unwrap) unless item_rep.unwrap.compiled?

        path_without_leading_slash = item_rep.path[1..-1]
        Sass::Script::String.new(path_without_leading_slash, :string)
      end

      private

      def find_item(identifier)
        context = options[:nanoc_current_filter]

        context.items.find_item!(identifier)
      end

      def item_rep_named(item, name)
        name = name.value if name.respond_to?(:value)
        rep = item.reps[name.to_sym]

        raise "No rep named '#{name}' for item: #{item.identifier}" unless rep
        rep
      end
    end
  end
end

module Sass
  module Script
    module Functions
      include Sass::Script::Items

      declare :i, [:identifier]
      declare :i, [:identifier], var_kwargs: true
    end
  end
end
```

(`@@counter` was just to get a small repro of the problem.)

**Comment by agross** [comment] 2017-02-28 23:21
I tried moving `depend_on` to my custom Sass filter, and it seems while most images are compiled before Sass, not all reps are.

```rb
require 'nanoc'

module Nanoc
  module Filters
    class SassWithCompass < Nanoc::Filter
      identifier :sass_with_compass
      type :text

      requires 'configatron', 'compass', 'sass'

      def initialize(assigns)
        super
        depend_on(@assigns[:items].find_all('/**/*.{jpg,png}'))
      end

      def run(content, params = {})
        render_with_sourcemap(sourcemap_uri) unless configatron.web.compress

        css, sourcemap = Sass.new(@assigns).setup_and_run(content,
                                                          configure_compass(params))

        if sourcemap
          IO.write(File.join(@config[:output_dir], sourcemap_file),
                   sourcemap.to_json(css_uri: @item.path))
        end

        css
      end

      private

      def configure_compass(params)
        p = params.dup
        Compass.add_project_configuration(p.delete(:config_file))

        p.merge(Compass.sass_engine_options)
      end

      def render_with_sourcemap(uri)
        ::Sass::Engine.send(:define_method,
                            :render,
                            proc { render_with_sourcemap(uri) })
      end

      def sourcemap_file
        @item.path + '.map'
      end

      def sourcemap_uri
        File.basename(sourcemap_file)
      end
    end
  end
end
```

**Comment by ddfreyne** [comment] 2017-03-03 17:52
Reopening for now.

**Comment by ddfreyne** [comment] 2017-03-03 18:16
I’ve created #1097, which I believe is a minimal reproduction of the issue you’re seeing.

**Comment by agross** [comment] 2017-03-03 18:23
Did you see #1093? Do you think they both share the same root cause?

**Comment by ddfreyne** [comment] 2017-03-03 18:28
I believe they are two unrelated issues. #1093 is a problem with `Filter#depend_on`, while `#1097` is a problem with `ItemRepView#raw_path`.

**Comment by ddfreyne** [comment] 2017-03-03 18:29
I’ll close this issue for now (replaced by #1093 and #1097).

**Closed by ddfreyne** 2017-03-03 18:29 UTC
Labels: bug
