### ISSUE TITLE
'compile' does not preserve "execute" file permission

### ISSUE THREAD

**Issue by sunshineco** [nanoc/nanoc#1232] opened 2017-10-17 11:18 UTC
`nanoc compile` drops _execute_ permission on text files. This is a big problem, for instance, for scripts deployed to `cgi-bin/`.

### Steps to reproduce

1. create a script (say, `/cgi-bin/foo.cgi`) in `content/`
2. ensure script is executable (`chmod +x cgi-bin/foo.cgi`)
3. mark the script as _text_ (`text_extensions: [ 'cgi' ]`)
4. compile the site

### Expected behavior

Compiled script should retain executable permission.

### Actual behavior

Compiled script lacks executable permission.

### Details

Permissions on _binary_ items are preserved, however, making a script _binary_ is not a solution if the script needs to be compiled (for instance, my `cgi-bin/` script is filtered by `:erb`).

This misbehavior impacts the compile/deploy cycle since it's easy to forget to fix the permissions before deployment.

**Comment by ddfreyne** [comment] 2017-10-17 18:43
Hmm, Nanoc doesn’t bother with file permissions at all. The fact that binary items retain their permission is only incidental.

The question here is whether or not it makes sense for Nanoc to support file permissions. This would be a larger undertaking, and would require some thought on how to make this work. For example, how would a `:chmod` filter work? Should ACLs be supported, and if so, on which platforms?

I’m inclined to not consider this a bug, but rather a feature request.

For the time being, I recommend doing some post-processing to `chmod` whatever is necessary. You can also use `nanoc check` with a custom check to ensure that the permissions are set up properly before a deploy.

**Comment by sunshineco** [comment] 2017-10-17 21:11
Fully supporting file permissions in the way you suggest would indeed be a large undertaking, but there is no need to jump immediately into the deep end of the pool. A pragmatic approach would satisfy this (obviously) legitimate real-world use-case in a way which is easy to reason about and to implement, and which does not lock you into some design which you would regret later. Take baby steps; add complexity only when shown to be necessary.

When approaching the problem from the shallow (pragmatic) end of the pool, the plan and implementation are much simpler. An obvious and conservative first approach is merely to (try to) restore *execute* permission on the output file if the input item is executable. Importantly, this approach does **not** lock you into *any* design and does *not* require you to think about and answer difficult questions about how to deal with ACLs or whether this should be handled by the core or by a filter (your `:chmod` example). It just works.

If, and only if, a real-world use-case arises where, for instance, a site needs *write* permission retained on an item, then the slightly less conservative approach of attempting a full `chmod` carry-over might be warranted. This also does *not* require heavy cogitation or lock you into a design you would regret.

If, and only if, a real-world use-case arises where ACLs or some unforeseen permission issues need to be handled, then, and only then, does it make sense to start thinking about the complexities you wrote about in your response. The pragmatic approach outlined here does not prevent you from implementing a more complex design in the future if shown necessary, nor is the suggested pragmatic approach merely an ugly hack; it's a legitimate solution which is likely to prove helpful without causing harm.

---

Using `postprocess` might be a reasonable interim answer, however, sparsity of documentation makes it difficult to determine if it would indeed be valid to do so. For instance, the `postprocess` [documentation](https://nanoc.ws/doc/rules/#post-processing) cites an example which only accesses in-memory item content; it does not say whether or not the output item has yet been written to the filesystem, so it does not answer the question of whether or not `postprocess` is the correct place for `chmod`. Moreover, there no longer seems to be *any* documented nanoc public API (at least I am unable to find it), so one can not easily know what, if any, methods an `item` supports, and whether or not its possible to retrieve an item's output filename.

**Comment by ddfreyne** [comment] 2017-10-18 06:20
I looked briefly at what it would take to implement permission handling in Nanoc. There’s no simple way to make it work; it’d require changes in the core entities (Item, ItemRep), data sources, core services (checksummer, dependency tracker, outdatedness checker), and probably elsewhere.

This is true even for the most trivial implementation of permissions.

This is a missing feature, not a bug (though the distinction between the two isn’t clear cut). I’ve created nanoc/features/issues/23 to track this.

* * *

As for postprocessing: a simple approach would be to invoke `chmod` after executing `nanoc`. The `postprocess` block is an alternative (available variables are [documented here](https://nanoc.ws/doc/reference/variables/)) though a bit overkill for this use case.

**Comment by ddfreyne** [comment] 2017-10-18 06:21
I’ll close this issue, but I’m happy to keep the conversation going, either in this thread or in nanoc/features/issues/23.

**Closed by ddfreyne** 2017-10-18 06:21 UTC

**Comment by sunshineco** [comment] 2017-10-18 11:28
Thanks, Denis. I don't consider `postprocess` overkill if it allows me to automate fixing of permissions on the output file so that I don't have to alter my build/deploy process. If `postprocess` saves me from having to deal with or think about the issue ever again (or at least in the long term), then I consider it a good pragmatic solution.

It's still not clear from the `postprocess` documentation whether one can rely upon the output files having been created before `postprocess` is invoked (as opposed to the outputs only being in memory), but I'll interpret your response as an affirmative that they have been saved to disk by `postprocess` time.

**Comment by ddfreyne** [comment] 2017-10-18 16:26
@sunshineco That’s correct — I’ve updated the documentation (https://github.com/nanoc/nanoc.ws/commit/7f139f537f098fee13b27d2c8252045dd74734a7) to make that more clear.

**Comment by sunshineco** [comment] 2017-10-18 20:30
Thanks, that change makes it clearer.
