### ISSUE TITLE
Errno::EPIPE: Broken pipe when running nanoc check css

### ISSUE THREAD

**Issue by lifepillar** [nanoc/nanoc#691] opened 2015-08-13 19:22 UTC
As the subject says, I get an error when running `nanoc check css`:

```
  Running check css…   
Captain! We’ve been hit!

Message:

Errno::EPIPE: Broken pipe

Compilation stack:

  (empty)

Stack trace:

  0. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:211:in `write'
  1. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
  2. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
  3. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
  4. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
  5. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:328:in `write_header'
  6. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:126:in `exec'
  7. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
  8. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
  9. /Users/me/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
  ... 34 more lines omitted. See full crash log for details.
```

All other checks work. Is this reproducible or is it something in my setup?

**Comment by lifepillar** [comment] 2015-08-14 07:43
In fact, on another site `nanoc check css` produces different errors: either

```
Errno::ECONNRESET: Connection reset by peer
```

or

```
W3CValidators::ValidatorUnavailable: unable to connect to the validator at http://jigsaw.w3.org/css-validator/validator (response was 400 "Bad request").
```

Which of the two seems to be random.

**Comment by ddfreyne** [comment] 2015-08-14 16:37
Are you using the most recent W3C validators gem? It sounds more like a problem within that gem rather than with nanoc itself.

**Comment by lifepillar** [comment] 2015-08-14 17:24
Yes, it's up to date. I'll try the gem directly and report the result.

**Comment by doc75** [comment] 2015-09-12 20:39
Hello,

I just had the same problem, and it was related to css file bootstrap.min.css.
When I temporarily remove this file from the output directory, the check is working fine.

Perhaps we could add a new setting to be able to list the css files to exclude from the check.
Your thoughts on this ?

**Comment by ddfreyne** [comment] 2015-09-18 18:53
This seems like an issue that’s not inside nanoc but in the W3C validators gem.

Does the gem directly (without using nanoc) work?

**Comment by doc75** [comment] 2015-09-20 13:09
You are correct, the w3c_validators gem has an issue with big files.
I fixed it through https://github.com/alexdunae/w3c_validators/pull/17, but not sure if this repo is still active.
If I have no answers in the coming week, I might start a community fork to publish a new version (waiting for repo owner answer so far).

**Comment by ddfreyne** [comment] 2015-09-27 18:16
Doesn’t look like the repo is active anymore. :/

I’ll close this issue since the problem is not within nanoc, but rather a dependency.

**Closed by ddfreyne** 2015-09-27 18:16 UTC
Labels: unclear
