### ISSUE TITLE
Accept 'write nil' as routing to nil

### ISSUE THREAD

**Issue by sunshineco** [nanoc/nanoc#1063] opened 2017-01-15 13:33 UTC
In a `compile` rule, interpret `write nil` the same as routing to `nil`.

### Steps to reproduce

~~~ruby
compile '/foo.*' do
    write nil
end
~~~

### Expected behavior

Item '/foo.*' should be routed to nil, just as if:

~~~ruby
route '/foo.*' do
    nil
end
~~~

had been specified.

### Actual behavior

Item '/foo.*' is unexpectedly routed by some other routing rule (typically, the catchall `route '/**/*'`, thus to `/foo/index.html`).

### Details

Given that simple routing rules can be expressed more concisely via `write` inside a `compile` rule, and that:

~~~ruby
compile '/foo.*' do
end

route '/foo.*' do
    '/foo/index.html'
end
~~~

can be transformed into:

~~~ruby
compile '/foo.*' do
    write '/foo/index.html'
end
~~~

one would intuitively expect that:

~~~ruby
compile '/foo.*' do
end

route '/foo.*' do
    nil
end
~~~

can likewise be transformed to:

~~~ruby
compile '/foo.*' do
    write nil
end
~~~

but this does not work as expected.

**Comment by ddfreyne** [comment] 2017-01-15 14:04
Definitely makes sense!

The way `snapshot` and `write` work together right now is a bit odd (and also the cause of #1037), so there’ll probably need to be a bit of refactoring to make this behave as expected.

I’ve marked this as an enhancement rather than a bug, but I guess it could be either.

**Comment by ddfreyne** [comment] 2017-03-16 07:49
Migrated to nanoc/features/issues/14.

**Closed by ddfreyne** 2017-03-16 07:49 UTC
Labels: enhancement
