### ISSUE TITLE
Nanoc crashes in presence of nil environments

### ISSUE THREAD

**Issue by gpakosz** [nanoc/nanoc#1352] opened 2018-09-09 17:36 UTC
Nanoc crashes in presence of empty environments instead of deferring everything to the default environment.

`nanoc.yaml`:
```
environments:
  default:
    foo: 'bar'
  xxx:
```

### Steps to reproduce

1. `nanoc create site`
2. `cd site`
2. `printf "environments:\n  default:\n    foo: 'bar'\n  xxx:\n" > nanoc.yaml
3. `nanoc compile`

### Expected behavior

The file compiles just fine.

### Actual behavior

Nanoc crashes with:
```
$ nanoc compile
Loading site… done
Compiling site…

Captain! We’ve been hit!

  ... 22 lines omitted (see crash.log for details)
  9. from /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/services/compiler.rb:25:in `new_for'
  8. from /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/services/compiler_loader.rb:37:in `load'
  7. from /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/services/compiler_loader.rb:37:in `new'
  6. from /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/services/compiler.rb:11:in `initialize'
  5. from /usr/local/lib/ruby/gems/2.5.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  4. from /usr/local/lib/ruby/gems/2.5.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
  3. from /usr/local/lib/ruby/gems/2.5.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
  2. from /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/entities/configuration.rb:164:in `output_dirs'
  1. from /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/entities/configuration.rb:164:in `map'
  /usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.19/lib/nanoc/base/entities/configuration.rb:164:in `block in output_dirs'

NoMethodError: undefined method `[]' for nil:NilClass
```

### Details

I tested with Nanoc version `4.8.19`.

**Comment by ddfreyne** [comment] 2018-09-10 15:46
I’d argue that this is not unexpected behavior, due to the way YAML works:

```ruby
YAML.parse('foo:')
# => {"foo"=>nil}
```

If you want an empty environment, you can specify it explicitly as `{}`:

```ruby
YAML.load('foo: {}')
# => {"foo"=>{}}
```

**Comment by gpakosz** [comment] 2018-09-10 15:56
But maybe could bail out with a nice error message?

**Comment by ddfreyne** [comment] 2018-09-11 20:02
This might fit in the larger “validate the configuration” issue — at the moment, it’s not explicitly validated at all.

```yaml
output_dir: true
# Should error with e.g. “expected output_dir to be a String, not `true`
```

```yaml
environments:
  production:
# Should error with e.g. “expected environments.production to be a Hash not `nil`
```

etc.

**Comment by ddfreyne** [comment] 2018-09-11 20:03
There is a feature request for this already (nanoc/features/issues/32) so I will close this issue, and continue in nanoc/features/issues/32.

**Closed by ddfreyne** 2018-09-11 20:03 UTC
