### ISSUE TITLE
NoMethodError: undefined method `green' for "ok":String

### ISSUE THREAD

**Issue by vesaoikonen** [nanoc/nanoc#1426] opened 2019-04-30 05:42 UTC
### Steps to reproduce

nanoc compile
nanoc check ilinks

### Expected behavior

Site compiled in 3.87s.
Loading site… done
  Running check internal_links…   ok

### Actual behavior

Loading site… done
  Running check internal_links…
Captain! We’ve been hit!

  ... 13 lines omitted (see crash.log for details)
  9. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/cli/error_handler.rb:15:in `handle_while'
  8. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/cli/error_handler.rb:57:in `handle_while'
  7. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/cli/error_handler.rb:15:in `block in handle_while'
  6. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/cli/command_runner.rb:14:in `block in call'
  5. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/cli/commands/check.rb:31:in `run'
  4. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/checking/runner.rb:52:in `run_specific'
  3. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/checking/runner.rb:70:in `run_check_classes'
  2. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/checking/runner.rb:98:in `run_checks'
  1. from /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/checking/runner.rb:98:in `each'
  /var/lib/gems/2.5.0/gems/nanoc-4.11.4/lib/nanoc/checking/runner.rb:109:in `block in run_checks'

NoMethodError: undefined method `color' for "ok":String

A detailed crash log has been written to ./crash.log.

### Solution

Edit runner.rb, add 
      require 'colored'
on line 92.

**Comment by ddfreyne** [comment] 2019-04-30 07:15
Thanks for reporting ! This is a duplicate of #1423, which is fixed but not yet released. A release is coming in the next few minutes…

**Closed by ddfreyne** 2019-04-30 07:15 UTC

**Comment by ddfreyne** [comment] 2019-04-30 07:21
This is now in the Nanoc 4.11.5 release.
