### ISSUE TITLE
Dependency problems with XSL filter and xsl:include

### ISSUE THREAD

**Issue by draconx** [nanoc/nanoc#924] opened 2016-08-02 17:33 UTC
Hi,

When using an XSL layout, nanoc does not seem to recognize included stylesheets as dependencies, and will not rebuild output files when the included stylesheets change.

I'd be happy with listing dependencies manually but as far as I can tell there is no way to do this; actually, I can't find anything in the documentation about how nanoc decides whether or not to rebuild a particular output file.

[Attached example site](https://github.com/nanoc/nanoc/files/397694/xsltdemo.tar.gz).  Build the site with nanoc, which generates output/index.xhtml.  Then edit layouts/snippet.xsl (for example, change the page title).  Expected behaviour is that rebuilding the site will update output/index.xhtml, but this does not happen.

Cheers,
Nick

xsltdemo.tar.gz: https://github.com/nanoc/nanoc/files/397694/xsltdemo.tar.gz

**Comment by ddfreyne** [comment] 2016-08-21 05:25
Nanoc indeed currently doesn’t handle dependencies `xsl:include`. It needs to be done manually, and I fear that this might not be an easy task, since it needs to handle transitive dependencies as well.

Marking as a bug, although it’s arguably perhaps a lacking feature.

**Comment by ddfreyne** [comment] 2016-08-22 09:57
As a workaround, you can delete the `tmp` directory in between builds. That directory stores dependency information, and lack of dependency information means that Nanoc will do a full rebuild. For sure not ideal, but it’ll help.

**Comment by ddfreyne** [comment] 2016-11-20 11:32
Ohh, I got this wrong. The problem is that there is not even a dependency from the item on the layout. A fix is coming up.

**Comment by ddfreyne** [comment] 2016-11-20 11:37
#996 has a fix for this issue.

**Comment by ddfreyne** [comment] 2016-11-20 11:39
Ack, nevermind—I’ve discovered a related issue, but the `xsl:include` elements not generating a dependency is still an open issue.

**Comment by ddfreyne** [comment] 2016-11-22 08:20
Accidentally automatically closed via a Git commit, sorry!

**Comment by ddfreyne** [comment] 2017-03-05 11:51
This issue is still relevant, but I believe that there is no way to fix this in a nice way. I have two ideas:

* Make the `xsl` filter depend on all items that have an `xsl` extension (either `/**/*.xsl` or `item[:extension] == 'xsl'`. This isn’t nice because it might tax Nanoc’s dependency generator a bit much.

* Mark the `xsl` filter as _always_ needing to be run, skipping the outdatedness check. This also isn’t super nice, and requires some changes in Nanoc to support this.

A proper solution might not be possible with Nokogiri (Nanoc would have to be able to generate the dependency graph of `xsl:include`s, which I don’t think is possible).

**Comment by ddfreyne** [comment] 2017-03-19 07:48
I have a fix in #1127. This fix marks the `xsl` filter always needing to be run (always marking the item rep as outdated). This isn’t ideal, but I couldn’t find a simple way to make Nokogiri report its dependencies (finding all `xsl:include`/`xsl:import`).

The fix will be in Nanoc 4.7.1.

**Closed** 2017-03-19 07:53 UTC
Labels: bug

**Comment by ddfreyne** [comment] 2017-03-19 07:55
Fixing this also closed the last known open issue in Nanoc!
